---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: lazarevic.david@relectronics.ch
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            ingressClassName: whoami-ingress

---
apiVersion: cert-manager.io/v1                                    
kind: Issuer                                                      
metadata:                                                         
  name: letsencrypt-prod
spec:                                          
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lazarevic.david@relectronics.ch                        
    privateKeySecretRef:                                          
      name: letsencrypt-prod                                   
    solvers:                                                      
      - http01:                                                   
          ingress:                                                
            ingressClassName: whoami-ingress                      